name: 'Action Two'
description: 'Second GitHub Action'
inputs:
  name:
    description: 'Your name'
    required: true
runs:
  using: 'node20'
  main: 'index.js'  # Add this line to specify the entry point
